### ISSUE TITLE
Configuration Mac path is incorrect

### ISSUE THREAD

**Issue by yhung119** [zellij-org/zellij-org.github.io#14]
I noticed on the configuration page (https://zellij.dev/documentation/configuration.html), the Mac path is incorrect. Should be `/Users/Alice/Library/Application Support/org.Zellij-Contributors.zellij` but shows `/Users/Alice/Library/Application Support/com.Zellij-Contributors.zellij`.

The documentation in the main branch is correct, so maybe there just hasn't been any new deployment since then?

**Comment by a-kenji** [comment]
Thank you for raising this issue!
This should be fixed now.
