### ISSUE TITLE
The result in my environment does not match the result in the overview page

### ISSUE THREAD

**Issue by takatea** [zellij-org/zellij-org.github.io#172]
I tried steps from 1 to 6 in [the overview page](https://zellij.dev/documentation/overview.html):

![image](https://user-images.githubusercontent.com/39912547/213090317-a5f7999f-3aaa-4772-8503-fb4dde545b60.png)

But, I actually got the following:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/39912547/213090817-3bb701c8-82d6-4dba-b607-647ee2a808bb.png">

Especially, `r` in the step 5 means a built-in command of zsh.

```bash
$ which r
r: shell built-in command
```

It seems `Ctrl+p` and `left arrow` instead of `r`:

```diff
Ctrl+t
n
Ctrl+p
n
++ Ctrl+p
++ ←
n
Return
```

Then, I got:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/39912547/213090950-6283c7e3-e100-4ff8-83e7-a935a318ad9f.png">

The description looks need to be updated, or any mistake in steps I did?

### Environment

```
macOS: version 12.3 
zsh: version: 5.9 (x86_64-apple-darwin21.3.0)
zellij 0.34.4 (installed by Cargo)
```

**Comment by imsnif** [comment]
Yes, good catch! This is very old and needs updating :) Would you like to submit a PR?

**Comment by takatea** [comment]
@imsnif, thank you for your reply!

>Would you like to submit a PR?

Yes, I would like to update description on the overview page by sending a PR!
In the PR,  could I be just modified the description of steps? 
Alternatively, would you like me to replace screenshots attached this issue from old version screenshots with it in the same PR?

**Comment by imsnif** [comment]
Thanks for this! Merged the PR just now.

**Comment by imsnif** [comment]
Sure, but I'd advise to wait for the next version (hopefully sometime in February) because we're adding some UI.

**Comment by takatea** [comment]
Thank you for reply!

>I'd advise to wait for the next version (hopefully sometime in February) because we're adding some UI.

I understand, I am eagerly anticipating the release of the next version!
